Repository acts-project/actions-test, pull requests merged in 2021-11, with the labels that each got.

#35 Update README.md
  README.md
Labels: automerge, WIP

#33 Create motrew
  motrew
Labels: Bug, documentation, automerge

#32 Create lkjhlkjh
  lkjhlkjh
Labels: automerge

#36 Create my new file.txt
  my new file.txt
Labels: Bug, automerge

#31 Create another one
  another one
Labels: automerge

#37 feat: Delete my new file.txt
  my new file.txt
Labels: automerge
